---
- name: Ensure that the procps package is installed
  tags: sysctl
  become: true
  apt:
    name: procps
    state: present
  when: ansible_os_family == 'Debian'

- name: Ensure that the procps package is installed
  tags: sysctl
  become: true
  yum:
    name: procps
    state: present
  when:
    - ansible_distribution_major_version <= '6'
    - ansible_os_family == 'RedHat'

- name: Ensure that the procps-ng package is installed
  tags: sysctl
  become: true
  yum:
    name: procps-ng
    state: present
  when:
    - ansible_distribution_major_version >= '7'
    - ansible_os_family == 'RedHat'

- name: Attempting to overlay sysctl.conf configurations
  tags: sysctl
  become: true
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: 0644
  notify: reload sysctl

- name: Attempting to overlay /etc/sysctl.d directory
  tags: sysctl
  become: true
  file:
    mode: 0755
    path: /etc/sysctl.d
    state: directory
  when: sysctl_d|length > 0

- name: Attempting to overlay sysctl.d configurations
  tags: sysctl
  become: true
  template:
    src: sysctl_d.j2
    dest: "{{ '/etc/sysctl.d/' + item.order|string + '-' + item.file + '.conf' }}"
    owner: root
    group: root
    mode: 0644
  notify: reload sysctl
  with_items: "{{ sysctl_d }}"
  loop_control:
    label: "{{ item.order|string + '-' + item.file }}"
  when:
    - item.file is defined
    - item.order is defined
    - item.settings|length > 0
...
