---
- name: Executing OS specific tasks (Debian)
  include_tasks: "{{ ansible_os_family|lower }}.yml"
  when: ansible_os_family == 'Debian'

- name: Executing OS specific tasks (RedHat)
  include_tasks: "{{ ansible_os_family|lower }}.yml"
  when: ansible_os_family == 'RedHat'

- name: Executing configuration tasks
  import_tasks: configure.yml
...
