---
- name: Ensure that the procps package is installed
  tags: sysctl
  become: true
  yum:
    name: procps
    state: present
  register: sysctl_package
  when: ansible_distribution_major_version <= '6'

- name: Ensure that the procps-ng package is installed
  tags: sysctl
  become: true
  yum:
    name: procps-ng
    state: present
  register: sysctl_package
  when: ansible_distribution_major_version >= '7'
...
